name: master
id: fed3f59d-9b32-4efe-a372-ca02d7ea9f66

registry:
  request_timeout: 2
  dial_timeout: 2
  client_config_key: tsunami_config_client_
  endpoints:
    - localhost:2379
    - localhost:22379
    - localhost:32379

