// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: services.proto

package tsgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TSAttach_Attach_FullMethodName = "/tsgrpc.TSAttach/Attach"
)

// TSAttachClient is the client API for TSAttach service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TSAttach is the worker->ocean control plane. A worker dials an ocean and
// keeps a single bidirectional stream open for its lifetime: it sends Register
// (once), then Reports/Heartbeats; the ocean sends Commands (start/stop).
type TSAttachClient interface {
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, OceanMessage], error)
}

type tSAttachClient struct {
	cc grpc.ClientConnInterface
}

func NewTSAttachClient(cc grpc.ClientConnInterface) TSAttachClient {
	return &tSAttachClient{cc}
}

func (c *tSAttachClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, OceanMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TSAttach_ServiceDesc.Streams[0], TSAttach_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, OceanMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TSAttach_AttachClient = grpc.BidiStreamingClient[WorkerMessage, OceanMessage]

// TSAttachServer is the server API for TSAttach service.
// All implementations must embed UnimplementedTSAttachServer
// for forward compatibility.
//
// TSAttach is the worker->ocean control plane. A worker dials an ocean and
// keeps a single bidirectional stream open for its lifetime: it sends Register
// (once), then Reports/Heartbeats; the ocean sends Commands (start/stop).
type TSAttachServer interface {
	Attach(grpc.BidiStreamingServer[WorkerMessage, OceanMessage]) error
	mustEmbedUnimplementedTSAttachServer()
}

// UnimplementedTSAttachServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTSAttachServer struct{}

func (UnimplementedTSAttachServer) Attach(grpc.BidiStreamingServer[WorkerMessage, OceanMessage]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedTSAttachServer) mustEmbedUnimplementedTSAttachServer() {}
func (UnimplementedTSAttachServer) testEmbeddedByValue()                  {}

// UnsafeTSAttachServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TSAttachServer will
// result in compilation errors.
type UnsafeTSAttachServer interface {
	mustEmbedUnimplementedTSAttachServer()
}

func RegisterTSAttachServer(s grpc.ServiceRegistrar, srv TSAttachServer) {
	// If the following call panics, it indicates UnimplementedTSAttachServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TSAttach_ServiceDesc, srv)
}

func _TSAttach_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TSAttachServer).Attach(&grpc.GenericServerStream[WorkerMessage, OceanMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TSAttach_AttachServer = grpc.BidiStreamingServer[WorkerMessage, OceanMessage]

// TSAttach_ServiceDesc is the grpc.ServiceDesc for TSAttach service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TSAttach_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tsgrpc.TSAttach",
	HandlerType: (*TSAttachServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _TSAttach_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}
