// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: services.proto

package tsgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HTTPMethod int32

const (
	HTTPMethod_GET    HTTPMethod = 0
	HTTPMethod_POST   HTTPMethod = 1
	HTTPMethod_PUT    HTTPMethod = 2
	HTTPMethod_DELETE HTTPMethod = 3
	HTTPMethod_UPDATE HTTPMethod = 4
)

// Enum value maps for HTTPMethod.
var (
	HTTPMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
		4: "UPDATE",
	}
	HTTPMethod_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
		"UPDATE": 4,
	}
)

func (x HTTPMethod) Enum() *HTTPMethod {
	p := new(HTTPMethod)
	*p = x
	return p
}

func (x HTTPMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTTPMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_services_proto_enumTypes[0].Descriptor()
}

func (HTTPMethod) Type() protoreflect.EnumType {
	return &file_services_proto_enumTypes[0]
}

func (x HTTPMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HTTPMethod.Descriptor instead.
func (HTTPMethod) EnumDescriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

// ---------- ocean -> worker ----------
type Action int32

const (
	Action_START Action = 0
	Action_STOP  Action = 1
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "START",
		1: "STOP",
	}
	Action_value = map[string]int32{
		"START": 0,
		"STOP":  1,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_services_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_services_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

type HTTPHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPHeader) Reset() {
	*x = HTTPHeader{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeader) ProtoMessage() {}

func (x *HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeader.ProtoReflect.Descriptor instead.
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HTTPHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Params describes a load test (carried by a START command).
type Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method        HTTPMethod             `protobuf:"varint,3,opt,name=method,proto3,enum=tsgrpc.HTTPMethod" json:"method,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Host          string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Concurrency   int32                  `protobuf:"varint,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Header        []*HTTPHeader          `protobuf:"bytes,9,rep,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	Verbose       bool                   `protobuf:"varint,11,opt,name=verbose,proto3" json:"verbose,omitempty"` // when true the worker records the last request/response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *Params) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Params) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Params) GetMethod() HTTPMethod {
	if x != nil {
		return x.Method
	}
	return HTTPMethod_GET
}

func (x *Params) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Params) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Params) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Params) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Params) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *Params) GetHeader() []*HTTPHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Params) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Params) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

// ---------- worker -> ocean ----------
type Register struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,3,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Register) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Register) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           string                 `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	WorkerCount   int32                  `protobuf:"varint,2,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	RequestCount  int64                  `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Avg           float64                `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Min           float64                `protobuf:"fixed64,6,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,7,opt,name=max,proto3" json:"max,omitempty"`
	Rps           float64                `protobuf:"fixed64,8,opt,name=rps,proto3" json:"rps,omitempty"`
	ElapsedTime   float64                `protobuf:"fixed64,9,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *Metric) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Metric) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *Metric) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *Metric) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *Metric) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *Metric) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Metric) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Metric) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *Metric) GetElapsedTime() float64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

// Sample is the last request/response a worker captured for a verbose job.
type Sample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	RequestHeader  []*HTTPHeader          `protobuf:"bytes,3,rep,name=request_header,json=requestHeader,proto3" json:"request_header,omitempty"`
	RequestBody    string                 `protobuf:"bytes,4,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	StatusCode     int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseHeader []*HTTPHeader          `protobuf:"bytes,6,rep,name=response_header,json=responseHeader,proto3" json:"response_header,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,7,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	LatencyMs      float64                `protobuf:"fixed64,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error          string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"` // set instead of a response when the request itself failed
	Ts             int64                  `protobuf:"varint,10,opt,name=ts,proto3" json:"ts,omitempty"`     // capture time, unix milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{4}
}

func (x *Sample) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Sample) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Sample) GetRequestHeader() []*HTTPHeader {
	if x != nil {
		return x.RequestHeader
	}
	return nil
}

func (x *Sample) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *Sample) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Sample) GetResponseHeader() []*HTTPHeader {
	if x != nil {
		return x.ResponseHeader
	}
	return nil
}

func (x *Sample) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *Sample) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Sample) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Sample) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Sample        *Sample                `protobuf:"bytes,2,opt,name=sample,proto3" json:"sample,omitempty"` // set only for verbose jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{5}
}

func (x *Report) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *Report) GetSample() *Sample {
	if x != nil {
		return x.Sample
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Report
	//	*WorkerMessage_Heartbeat
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetReport() *Report {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Report struct {
	Report *Report `protobuf:"bytes,2,opt,name=report,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Msg() {}

func (*WorkerMessage_Report) isWorkerMessage_Msg() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Msg() {}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=tsgrpc.Action" json:"action,omitempty"`
	Job           string                 `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Params        *Params                `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // set for START
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_START
}

func (x *Command) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Command) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type OceanMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*OceanMessage_Command
	Msg           isOceanMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OceanMessage) Reset() {
	*x = OceanMessage{}
	mi := &file_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OceanMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OceanMessage) ProtoMessage() {}

func (x *OceanMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OceanMessage.ProtoReflect.Descriptor instead.
func (*OceanMessage) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{9}
}

func (x *OceanMessage) GetMsg() isOceanMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *OceanMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Msg.(*OceanMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isOceanMessage_Msg interface {
	isOceanMessage_Msg()
}

type OceanMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

func (*OceanMessage_Command) isOceanMessage_Msg() {}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\x06tsgrpc\"4\n" +
	"\n" +
	"HTTPHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xae\x02\n" +
	"\x06Params\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12*\n" +
	"\x06method\x18\x03 \x01(\x0e2\x12.tsgrpc.HTTPMethodR\x06method\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x06 \x01(\tR\x04port\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12 \n" +
	"\vconcurrency\x18\b \x01(\x05R\vconcurrency\x12*\n" +
	"\x06header\x18\t \x03(\v2\x12.tsgrpc.HTTPHeaderR\x06header\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\x12\x18\n" +
	"\averbose\x18\v \x01(\bR\averbose\"d\n" +
	"\bRegister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fmax_concurrency\x18\x03 \x01(\x05R\x0emaxConcurrency\"\xee\x01\n" +
	"\x06Metric\x12\x10\n" +
	"\x03job\x18\x01 \x01(\tR\x03job\x12!\n" +
	"\fworker_count\x18\x02 \x01(\x05R\vworkerCount\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x03R\n" +
	"errorCount\x12\x10\n" +
	"\x03avg\x18\x05 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03min\x18\x06 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\a \x01(\x01R\x03max\x12\x10\n" +
	"\x03rps\x18\b \x01(\x01R\x03rps\x12!\n" +
	"\felapsed_time\x18\t \x01(\x01R\velapsedTime\"\xd8\x02\n" +
	"\x06Sample\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x129\n" +
	"\x0erequest_header\x18\x03 \x03(\v2\x12.tsgrpc.HTTPHeaderR\rrequestHeader\x12!\n" +
	"\frequest_body\x18\x04 \x01(\tR\vrequestBody\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12;\n" +
	"\x0fresponse_header\x18\x06 \x03(\v2\x12.tsgrpc.HTTPHeaderR\x0eresponseHeader\x12#\n" +
	"\rresponse_body\x18\a \x01(\tR\fresponseBody\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x01R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x0e\n" +
	"\x02ts\x18\n" +
	" \x01(\x03R\x02ts\"X\n" +
	"\x06Report\x12&\n" +
	"\x06metric\x18\x01 \x01(\v2\x0e.tsgrpc.MetricR\x06metric\x12&\n" +
	"\x06sample\x18\x02 \x01(\v2\x0e.tsgrpc.SampleR\x06sample\"\x1b\n" +
	"\tHeartbeat\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\"\xa3\x01\n" +
	"\rWorkerMessage\x12.\n" +
	"\bregister\x18\x01 \x01(\v2\x10.tsgrpc.RegisterH\x00R\bregister\x12(\n" +
	"\x06report\x18\x02 \x01(\v2\x0e.tsgrpc.ReportH\x00R\x06report\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.tsgrpc.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"k\n" +
	"\aCommand\x12&\n" +
	"\x06action\x18\x01 \x01(\x0e2\x0e.tsgrpc.ActionR\x06action\x12\x10\n" +
	"\x03job\x18\x02 \x01(\tR\x03job\x12&\n" +
	"\x06params\x18\x03 \x01(\v2\x0e.tsgrpc.ParamsR\x06params\"B\n" +
	"\fOceanMessage\x12+\n" +
	"\acommand\x18\x01 \x01(\v2\x0f.tsgrpc.CommandH\x00R\acommandB\x05\n" +
	"\x03msg*@\n" +
	"\n" +
	"HTTPMethod\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x04*\x1d\n" +
	"\x06Action\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x012G\n" +
	"\bTSAttach\x12;\n" +
	"\x06Attach\x12\x15.tsgrpc.WorkerMessage\x1a\x14.tsgrpc.OceanMessage\"\x00(\x010\x01B!Z\x1fgithub.com/tsunami/proto;tsgrpcb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_proto_goTypes = []any{
	(HTTPMethod)(0),       // 0: tsgrpc.HTTPMethod
	(Action)(0),           // 1: tsgrpc.Action
	(*HTTPHeader)(nil),    // 2: tsgrpc.HTTPHeader
	(*Params)(nil),        // 3: tsgrpc.Params
	(*Register)(nil),      // 4: tsgrpc.Register
	(*Metric)(nil),        // 5: tsgrpc.Metric
	(*Sample)(nil),        // 6: tsgrpc.Sample
	(*Report)(nil),        // 7: tsgrpc.Report
	(*Heartbeat)(nil),     // 8: tsgrpc.Heartbeat
	(*WorkerMessage)(nil), // 9: tsgrpc.WorkerMessage
	(*Command)(nil),       // 10: tsgrpc.Command
	(*OceanMessage)(nil),  // 11: tsgrpc.OceanMessage
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: tsgrpc.Params.method:type_name -> tsgrpc.HTTPMethod
	2,  // 1: tsgrpc.Params.header:type_name -> tsgrpc.HTTPHeader
	2,  // 2: tsgrpc.Sample.request_header:type_name -> tsgrpc.HTTPHeader
	2,  // 3: tsgrpc.Sample.response_header:type_name -> tsgrpc.HTTPHeader
	5,  // 4: tsgrpc.Report.metric:type_name -> tsgrpc.Metric
	6,  // 5: tsgrpc.Report.sample:type_name -> tsgrpc.Sample
	4,  // 6: tsgrpc.WorkerMessage.register:type_name -> tsgrpc.Register
	7,  // 7: tsgrpc.WorkerMessage.report:type_name -> tsgrpc.Report
	8,  // 8: tsgrpc.WorkerMessage.heartbeat:type_name -> tsgrpc.Heartbeat
	1,  // 9: tsgrpc.Command.action:type_name -> tsgrpc.Action
	3,  // 10: tsgrpc.Command.params:type_name -> tsgrpc.Params
	10, // 11: tsgrpc.OceanMessage.command:type_name -> tsgrpc.Command
	9,  // 12: tsgrpc.TSAttach.Attach:input_type -> tsgrpc.WorkerMessage
	11, // 13: tsgrpc.TSAttach.Attach:output_type -> tsgrpc.OceanMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_services_proto_msgTypes[7].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Report)(nil),
		(*WorkerMessage_Heartbeat)(nil),
	}
	file_services_proto_msgTypes[9].OneofWrappers = []any{
		(*OceanMessage_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		EnumInfos:         file_services_proto_enumTypes,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
