// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: services.proto

package tsgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request_CommandType int32

const (
	Request_START        Request_CommandType = 0
	Request_RESTART      Request_CommandType = 1
	Request_STOP         Request_CommandType = 2
	Request_GET_METRICES Request_CommandType = 3
)

// Enum value maps for Request_CommandType.
var (
	Request_CommandType_name = map[int32]string{
		0: "START",
		1: "RESTART",
		2: "STOP",
		3: "GET_METRICES",
	}
	Request_CommandType_value = map[string]int32{
		"START":        0,
		"RESTART":      1,
		"STOP":         2,
		"GET_METRICES": 3,
	}
)

func (x Request_CommandType) Enum() *Request_CommandType {
	p := new(Request_CommandType)
	*p = x
	return p
}

func (x Request_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_services_proto_enumTypes[0].Descriptor()
}

func (Request_CommandType) Type() protoreflect.EnumType {
	return &file_services_proto_enumTypes[0]
}

func (x Request_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_CommandType.Descriptor instead.
func (Request_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0, 0}
}

type Request_HTTPMethod int32

const (
	Request_GET    Request_HTTPMethod = 0
	Request_POST   Request_HTTPMethod = 1
	Request_PUT    Request_HTTPMethod = 2
	Request_DELETE Request_HTTPMethod = 3
	Request_UPDATE Request_HTTPMethod = 4
)

// Enum value maps for Request_HTTPMethod.
var (
	Request_HTTPMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
		4: "UPDATE",
	}
	Request_HTTPMethod_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
		"UPDATE": 4,
	}
)

func (x Request_HTTPMethod) Enum() *Request_HTTPMethod {
	p := new(Request_HTTPMethod)
	*p = x
	return p
}

func (x Request_HTTPMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_HTTPMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_services_proto_enumTypes[1].Descriptor()
}

func (Request_HTTPMethod) Type() protoreflect.EnumType {
	return &file_services_proto_enumTypes[1]
}

func (x Request_HTTPMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_HTTPMethod.Descriptor instead.
func (Request_HTTPMethod) EnumDescriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0, 1}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       Request_CommandType    `protobuf:"varint,1,opt,name=command,proto3,enum=tsgrpc.Request_CommandType" json:"command,omitempty"`
	Params        *Request_Params        `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetCommand() Request_CommandType {
	if x != nil {
		return x.Command
	}
	return Request_START
}

func (x *Request) GetParams() *Request_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Request) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxConcurrences int32                  `protobuf:"varint,3,opt,name=maxConcurrences,proto3" json:"maxConcurrences,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetMaxConcurrences() int32 {
	if x != nil {
		return x.MaxConcurrences
	}
	return 0
}

type Request_HTTPHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_HTTPHeader) Reset() {
	*x = Request_HTTPHeader{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_HTTPHeader) ProtoMessage() {}

func (x *Request_HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_HTTPHeader.ProtoReflect.Descriptor instead.
func (*Request_HTTPHeader) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_HTTPHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request_HTTPHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Request_Params struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method          Request_HTTPMethod     `protobuf:"varint,3,opt,name=method,proto3,enum=tsgrpc.Request_HTTPMethod" json:"method,omitempty"`
	Protocol        string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Host            string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Port            string                 `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
	Path            string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	MaxConcurrences int32                  `protobuf:"varint,8,opt,name=maxConcurrences,proto3" json:"maxConcurrences,omitempty"`
	Header          []*Request_HTTPHeader  `protobuf:"bytes,9,rep,name=header,proto3" json:"header,omitempty"`
	Body            string                 `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request_Params) Reset() {
	*x = Request_Params{}
	mi := &file_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Params) ProtoMessage() {}

func (x *Request_Params) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Params.ProtoReflect.Descriptor instead.
func (*Request_Params) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Request_Params) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request_Params) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request_Params) GetMethod() Request_HTTPMethod {
	if x != nil {
		return x.Method
	}
	return Request_GET
}

func (x *Request_Params) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Request_Params) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Request_Params) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Request_Params) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request_Params) GetMaxConcurrences() int32 {
	if x != nil {
		return x.MaxConcurrences
	}
	return 0
}

func (x *Request_Params) GetHeader() []*Request_HTTPHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Request_Params) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\x06tsgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x05\n" +
	"\aRequest\x125\n" +
	"\acommand\x18\x01 \x01(\x0e2\x1b.tsgrpc.Request.CommandTypeR\acommand\x12.\n" +
	"\x06params\x18\x02 \x01(\v2\x16.tsgrpc.Request.ParamsR\x06params\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a4\n" +
	"\n" +
	"HTTPHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1a\xac\x02\n" +
	"\x06Params\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x122\n" +
	"\x06method\x18\x03 \x01(\x0e2\x1a.tsgrpc.Request.HTTPMethodR\x06method\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x06 \x01(\tR\x04port\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12(\n" +
	"\x0fmaxConcurrences\x18\b \x01(\x05R\x0fmaxConcurrences\x122\n" +
	"\x06header\x18\t \x03(\v2\x1a.tsgrpc.Request.HTTPHeaderR\x06header\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\"A\n" +
	"\vCommandType\x12\t\n" +
	"\x05START\x10\x00\x12\v\n" +
	"\aRESTART\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\x10\n" +
	"\fGET_METRICES\x10\x03\"@\n" +
	"\n" +
	"HTTPMethod\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x04\"=\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"_\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x0fmaxConcurrences\x18\x03 \x01(\x05R\x0fmaxConcurrences2\x82\x02\n" +
	"\tTSControl\x12,\n" +
	"\x05Start\x12\x0f.tsgrpc.Request\x1a\x10.tsgrpc.Response\"\x00\x12+\n" +
	"\x04Stop\x12\x0f.tsgrpc.Request\x1a\x10.tsgrpc.Response\"\x00\x12.\n" +
	"\aRestart\x12\x0f.tsgrpc.Request\x1a\x10.tsgrpc.Response\"\x00\x121\n" +
	"\n" +
	"GetMetrics\x12\x0f.tsgrpc.Request\x1a\x10.tsgrpc.Response\"\x00\x127\n" +
	"\bRegister\x12\x17.tsgrpc.RegisterRequest\x1a\x10.tsgrpc.Response\"\x00B!Z\x1fgithub.com/tsunami/proto;tsgrpcb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_proto_goTypes = []any{
	(Request_CommandType)(0),      // 0: tsgrpc.Request.CommandType
	(Request_HTTPMethod)(0),       // 1: tsgrpc.Request.HTTPMethod
	(*Request)(nil),               // 2: tsgrpc.Request
	(*Response)(nil),              // 3: tsgrpc.Response
	(*RegisterRequest)(nil),       // 4: tsgrpc.RegisterRequest
	(*Request_HTTPHeader)(nil),    // 5: tsgrpc.Request.HTTPHeader
	(*Request_Params)(nil),        // 6: tsgrpc.Request.Params
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: tsgrpc.Request.command:type_name -> tsgrpc.Request.CommandType
	6,  // 1: tsgrpc.Request.params:type_name -> tsgrpc.Request.Params
	7,  // 2: tsgrpc.Request.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: tsgrpc.Request.Params.method:type_name -> tsgrpc.Request.HTTPMethod
	5,  // 4: tsgrpc.Request.Params.header:type_name -> tsgrpc.Request.HTTPHeader
	2,  // 5: tsgrpc.TSControl.Start:input_type -> tsgrpc.Request
	2,  // 6: tsgrpc.TSControl.Stop:input_type -> tsgrpc.Request
	2,  // 7: tsgrpc.TSControl.Restart:input_type -> tsgrpc.Request
	2,  // 8: tsgrpc.TSControl.GetMetrics:input_type -> tsgrpc.Request
	4,  // 9: tsgrpc.TSControl.Register:input_type -> tsgrpc.RegisterRequest
	3,  // 10: tsgrpc.TSControl.Start:output_type -> tsgrpc.Response
	3,  // 11: tsgrpc.TSControl.Stop:output_type -> tsgrpc.Response
	3,  // 12: tsgrpc.TSControl.Restart:output_type -> tsgrpc.Response
	3,  // 13: tsgrpc.TSControl.GetMetrics:output_type -> tsgrpc.Response
	3,  // 14: tsgrpc.TSControl.Register:output_type -> tsgrpc.Response
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		EnumInfos:         file_services_proto_enumTypes,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
